## Exim special configuration
EXIMLOCAL=/opt/local/etc/exim/configure.local
echo "## File generated by mdata-setup script" > $EXIMLOCAL

# Hostname 
echo "PRIMARY_HOSTNAME = $(/usr/sbin/mdata-get sdc:hostname)" >> $EXIMLOCAL

# Administrativ Emailaddress
ADMIN_CONTACT='root'

if ADMIN_CONTACT=$(/usr/sbin/mdata-get rfc2142_mail 2>/dev/null) || \
   ADMIN_CONTACT=$(/usr/sbin/mdata-get mail_adminaddr 2>/dev/null); then
        echo "ADMIN_CONTACT = ${ADMIN_CONTACT:='root'}" >> $EXIMLOCAL
fi

# Default DKIM
mdata-get dkim_private_key > /opt/local/etc/exim/domain.key
echo "DEFAULT_DOMAINKEY = /opt/local/etc/exim/domain.key" >> $EXIMLOCAL

if mdata-get dkim_selector 1>/dev/null 2>&1; then
        echo "DKIM_SELECTOR = $(mdata-get dkim_selector)" >> $EXIMLOCAL
else
        echo "DKIM_SELECTOR = dkim" >> $EXIMLOCAL
fi

# create cronjob for exim panic log check and tinydb
CRON='25 6 * * * /opt/core/bin/exim-cron.sh'
(crontab -l 2>/dev/null || true; echo "$CRON" ) | sort | uniq | crontab

# enable exim service
/usr/sbin/svcadm enable svc:/pkgsrc/exim:default
