#!/usr/bin/bash
#
# Put customizations to your image in this file.

MUNIN_PLUGIN_VERSION='0.2'

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

echo "* Install spiped"
pkg_add http://pkgsrc.smartos.skylime.net/skylime-extra/2014Q1/x86_64/spiped-1.3.1nb3.tgz

echo "* Enable mdata-setup script"
svccfg import /tmp/mdata-setup.xml
rm /tmp/mdata-setup.xml

echo "* Create clamav logging directory"
mkdir -p /var/log/clamav
chown clamav:clamav /var/log/clamav

echo "* Create ssl folder"
mkdir -p /opt/local/etc/exim/ssl

# Create extra user for spamd
echo "* Create spamd group and user"
groupadd spamd
useradd -d /var/spamassassin -c "spamassassin spamd user" -s /usr/bin/false -g spamd spamd
passwd -N spamd

# Change default permissions for spamd folder
echo "* Update permissions for spamassassin folders"
chown -R spamd:spamd /var/spamassassin
chown -R spamd:spamd /opt/local/etc/spamassassin

# Import spamd manifest
echo "* Import spamd manifest"
svccfg import /tmp/spamd.xml
rm /tmp/spamd.xml

# Import exim manifest
echo "* Import exim manifest"
svccfg import /tmp/exim.xml
rm /tmp/exim.xml

# Update spamd and clamd
echo "* Update spamd and clamd database"
/opt/local/bin/freshclam

# Create munin template file that will be used during mdata setup
echo "* Create munin template file that will be used during mdata setup"
cp /opt/local/etc/munin/munin-node.conf /opt/local/etc/munin/munin-node.conf.tpl

# Download and install community munin plugins
echo "* Download and install community munin plugins (overwrite all other plugins)"
curl -L https://github.com/drscream/smartos-munin-plugins/archive/v${MUNIN_PLUGIN_VERSION}.tar.gz | tar xz -C /opt/local/lib/munin/plugins

pyzor --homedir /opt/local/etc/spamassassin discover

# Configuring image specific packages
echo "* Configuring image specific packages.";
# Exim
pkg_add http://pkgsrc.smartos.skylime.net/skylime-extra/2014Q1/x86_64/hiredis-0.11.0.tgz
pkg_add http://pkgsrc.smartos.skylime.net/skylime-extra/2014Q1/x86_64/exim-4.82nb1.tgz

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y

