#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
	clamav
	exim_mailqueue
	exim_mailstats
	spamassassin
	redis_replication_status
"

# Exit if any commands fail
set -o errexit

echo "* Create clamav logging directory"
mkdir -p /var/log/clamav
chown clamav:clamav /var/log/clamav

echo "* Create ssl folder"
mkdir -p /opt/local/etc/exim/ssl

# Create extra user for spamd
echo "* Create spamd group and user"
groupadd spamd
useradd -d /var/spamassassin -c "spamassassin spamd user" -s /usr/bin/false -g spamd spamd
passwd -N spamd

# Change default permissions for spamd folder
echo "* Update permissions for spamassassin folders"
mkdir /var/spamassassin/.spamassassin
chown -R spamd:spamd /var/spamassassin
chown -R spamd:spamd /opt/local/etc/spamassassin

# Create logging folder for spamd
echo "* Create logging folder for spamd"
mkdir /var/log/spamd
chown -R spamd:spamd /var/log/spamd

# Update spamd and clamd
echo "* Update spamd and clamd database"
/opt/local/bin/freshclam
pyzor --homedir /opt/local/etc/spamassassin discover

echo "* Copy mailer.conf to /etc/ because of exim usage"
cp /opt/local/share/examples/exim/mailer.conf /etc/

# Remove all examples dovecot configuration
echo "* Remove all examples dovecot configuration"
shopt -s extglob
rm -f /opt/local/etc/dovecot/conf.d/!(core-*)
rm -f /opt/local/etc/dovecot/*.ext
rm -f /opt/local/etc/dovecot/dovecot-example.conf

# Create ssl folder
echo "* Create ssl folder"
mkdir -p /opt/local/etc/dovecot/ssl

echo "* Create log folder for dovecot"
mkdir -p /var/log/dovecot

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

echo "* Cleaning up"
rm -rf /root/*
sm-prepare-image -y
