#!/bin/bash
# Configure exim with mdata information

# for SSL
mdata-get mx_ssl > /opt/local/etc/exim/ssl/exim.pem
chmod 400 /opt/local/etc/exim/ssl/exim.pem

## Exim special configuration
EXIMLOCAL=/opt/local/etc/exim/configure.local
echo "## File generated by mdata-setup script" > $EXIMLOCAL

# Default Domainkey
mdata-get domainkey > /opt/local/etc/exim/domain.key
echo "DEFAULT_DOMAINKEY = /opt/local/etc/exim/domain.key" >> $EXIMLOCAL

# Secrets for SRS-Hash
# Define old an new to be able to change secrets
echo "SRS_SECRET = $(mdata-get srs_secret)" >> $EXIMLOCAL
echo "SRS_OLD_SECRET = $(mdata-get srs_secret_old)" >> $EXIMLOCAL
