#!/bin/bash
# Configure exim with mdata information

# for SSL
mdata-get submission_ssl > /opt/local/etc/exim/ssl/exim.pem
chmod 400 /opt/local/etc/exim/ssl/exim.pem
chown mail /opt/local/etc/exim/ssl/exim.pem

## Exim special configuration
EXIMLOCAL=/opt/local/etc/exim/configure.local
echo "## File generated by mdata-setup script" > $EXIMLOCAL

# Hostname
echo "primary_hostname = $(/usr/sbin/mdata-get sdc:hostname)" >> $EXIMLOCAL

# Administrativ Emailaddress
RFC2142_MAIL=$(/usr/sbin/mdata-get rfc2142_mail 2>/dev/null)
MAIL_ADMINADDR=$(/usr/sbin/mdata-get mail_adminaddr 2>/dev/null)
echo "ADMIN_CONTACT = ${RFC2142_MAIL:-${MAIL_ADMINADDR:='root'}}" >> $EXIMLOCAL

# Default DKIM
mdata-get dkim_private_key > /opt/local/etc/exim/domain.key
echo "DEFAULT_DOMAINKEY = /opt/local/etc/exim/domain.key" >> $EXIMLOCAL

if mdata-get dkim_selector 1>/dev/null 2>&1; then
	echo "DKIM_SELECTOR = $(mdata-get dkim_selector)" >> $EXIMLOCAL
else
	echo "DKIM_SELECTOR = dkim" >> $EXIMLOCAL
fi
